/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
//        MainApp classUnderTest = new MainApp();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
