/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import Sudoku.controller.MainAppController;
import Sudoku.controller.StartController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class MainApp extends Application {

	private Stage primaryStage;
	private AnchorPane rootLayout;
	private Scene scene;


	public MainApp() {



	}

	@Override
	public void start(Stage primaryStage) {

		this.primaryStage = primaryStage;
		this.primaryStage.setTitle("Sudoku");
		this.primaryStage.setMaximized(true);
		this.primaryStage.setResizable(false);

		initRootLayout();
		initStartLayout();
	}

	public void initStartLayout() {


		try {
			FXMLLoader loader = new FXMLLoader();
			loader.setLocation(MainApp.class.getResource("../fxml Dateien/Start.fxml"));
			VBox v = (VBox) loader.load();
//			rootLayout.setPrefHeight(Toolkit.getDefaultToolkit().getScreenSize().getHeight() * 0.9);
//			rootLayout.setPrefWidth(Toolkit.getDefaultToolkit().getScreenSize().getWidth());

			StartController controller = loader.getController();
			controller.setMainApp(this);
			
			controller.startwerteSetzen();

			this.rootLayout.getChildren().add(v);
//			this.scene = new Scene(rootLayout);
//			primaryStage.setScene(scene);
//			primaryStage.show();

			System.out.println("Startlayout erfolgreich!");

		} catch (Exception e) {

			fehlerBeimLadenVonFxmlDateiAnzeigen("Startlayout: " + e.getMessage());
			System.out.println("Startlayout: " + e.getMessage());

		}

	}
	
	public void initRootLayout() {


		try {
			FXMLLoader loader = new FXMLLoader();
			loader.setLocation(MainApp.class.getResource("../fxml Dateien/Main.fxml"));
			this.rootLayout = (AnchorPane) loader.load();
//			rootLayout.setPrefHeight(Toolkit.getDefaultToolkit().getScreenSize().getHeight() * 0.9);
//			rootLayout.setPrefWidth(Toolkit.getDefaultToolkit().getScreenSize().getWidth());

			MainAppController controller = loader.getController();
			controller.setMainApp(this);
			controller.startwerteSetzen();

			this.scene = new Scene(rootLayout);
			primaryStage.setScene(scene);
			primaryStage.show();

			System.out.println("Rootlayout erfolgreich!");

		} catch (Exception e) {

			fehlerBeimLadenVonFxmlDateiAnzeigen("Rootlayout: " + e.getMessage());
			System.out.println("Rootlayout: " + e.getMessage());

		}

	}
	
	public void initLösungsLayout() {


		try {
			FXMLLoader loader = new FXMLLoader();
			loader.setLocation(MainApp.class.getResource("../fxml Dateien/Lösung.fxml"));
			VBox v = (VBox) loader.load();
//			rootLayout.setPrefHeight(Toolkit.getDefaultToolkit().getScreenSize().getHeight() * 0.9);
//			rootLayout.setPrefWidth(Toolkit.getDefaultToolkit().getScreenSize().getWidth());

			MainAppController controller = loader.getController();
			controller.setMainApp(this);
			controller.startwerteSetzen();

			this.scene = new Scene(rootLayout);
			primaryStage.setScene(scene);
			primaryStage.show();

			System.out.println("Rootlayout erfolgreich!");

		} catch (Exception e) {

			fehlerBeimLadenVonFxmlDateiAnzeigen("Rootlayout: " + e.getMessage());
			System.out.println("Rootlayout: " + e.getMessage());

		}

	}

	
	public static void fehlerBeimLadenVonFxmlDateiAnzeigen(String message) {
		Alert alert = new Alert(AlertType.ERROR);
		alert.setTitle("Ein Fehler ist aufgetreten!");
		alert.setHeaderText("Fehler beim Laden der fxml-Datei!");
		alert.setContentText(message);

		alert.showAndWait();
	}

	public static void unbekanntenFehlerAnzeigen(String message) {
		Alert alert = new Alert(AlertType.ERROR);
		alert.setTitle("Ein Fehler ist aufgetreten!");
		alert.setHeaderText("Unbekannter Fehler!");
		alert.setContentText(message);

		alert.showAndWait();
	}

	public static void main(String[] args) {
		launch(args);
	}

	public Stage getPrimaryStage() {
		return primaryStage;
	}

	public AnchorPane getRootLayout() {
		return rootLayout;
	}

	public Scene getScene() {
		return scene;
	}

}

